package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tally</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--red:#c44040;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:700px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.btn-s{border-color:var(--green);color:var(--green)}.btn-s:hover{background:var(--green);color:var(--bg)}.ctr-row{display:flex;align-items:center;gap:.6rem;padding:.5rem;background:var(--bg2);border:1px solid var(--bg3);margin-bottom:.3rem}.ctr-name{flex:1;font-weight:600}.ctr-val{font-size:1.3rem;font-weight:700;color:var(--gold);min-width:60px;text-align:right}.ctr-ns{font-size:.6rem;padding:.05rem .25rem;background:var(--bg3);color:var(--ll);border-radius:2px}.ctr-btns{display:flex;gap:.2rem}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:400px}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=number]{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Tally</span></h1><button class="btn btn-p" onclick="showNew()">+ Counter</button></div>
<div class="main"><div id="upgrade-banner" style="display:none;background:#241e18;border:1px solid #8b3d1a;border-left:3px solid #c45d2c;padding:.6rem 1rem;font-size:.78rem;color:#bfb5a3;margin-bottom:.8rem"><strong style="color:#f0e6d3">Free tier</strong> — 10 items max. <a href="https://stockyard.dev/tally/" target="_blank" style="color:#e8753a">Upgrade to Pro →</a></div><div id="list"></div></div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
async function load(){const d=await api('/api/counters');const ctrs=d.counters||[];
document.getElementById('list').innerHTML=ctrs.length?ctrs.map(c=>
'<div class="ctr-row"><span class="ctr-ns">'+esc(c.namespace)+'</span><span class="ctr-name">'+esc(c.name)+'</span><span class="ctr-val">'+c.value+'</span><div class="ctr-btns"><button class="btn btn-s" style="font-size:.6rem;padding:.15rem .3rem" onclick="inc(\''+esc(c.name)+'\',\''+esc(c.namespace)+'\',1)">+1</button><button class="btn btn-s" style="font-size:.6rem;padding:.15rem .3rem" onclick="inc(\''+esc(c.name)+'\',\''+esc(c.namespace)+'\',-1)">-1</button><button class="btn btn-p" style="font-size:.6rem;padding:.15rem .3rem" onclick="inc(\''+esc(c.name)+'\',\''+esc(c.namespace)+'\',10)">+10</button></div><span style="cursor:pointer;font-size:.55rem;color:var(--cm)" onclick="del(\''+c.id+'\')">del</span></div>'
).join(''):'<div class="empty">No counters yet. POST /api/increment to auto-create.</div>'}
async function inc(name,ns,by){await api('/api/increment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,namespace:ns,by})});load()}
async function del(id){await api('/api/counters/'+id,{method:'DELETE'});load()}
function showNew(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>New Counter</h2><label class="fl">Name</label><input type="text" id="nc-name" placeholder="page_views"><label class="fl">Namespace</label><input type="text" id="nc-ns" value="default"><label class="fl">Initial Value</label><input type="number" id="nc-val" value="0"><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="save()">Create</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function save(){const b={name:document.getElementById('nc-name').value,namespace:document.getElementById('nc-ns').value||'default',value:parseInt(document.getElementById('nc-val').value)||0};if(!b.name){alert('Name required');return};await api('/api/counters',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load()}
function closeModal(){document.getElementById('modal').innerHTML=''}
load();setInterval(load,5000)
fetch('/api/tier').then(r=>r.json()).then(j=>{if(j.tier==='free'){var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'}}).catch(()=>{var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'});
</script></body></html>`
