package store
import("database/sql";"encoding/json";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Form struct{ID int64 `json:"id"`;Name string `json:"name"`;Description string `json:"description"`;Fields string `json:"fields"`;Active bool `json:"active"`;CreatedAt time.Time `json:"created_at"`;ResponseCount int `json:"response_count,omitempty"`}
type Response struct{ID int64 `json:"id"`;FormID int64 `json:"form_id"`;Data string `json:"data"`;IP string `json:"ip"`;CreatedAt time.Time `json:"created_at"`}
func Open(dataDir string)(*DB,error){if err:=os.MkdirAll(dataDir,0755);err!=nil{return nil,fmt.Errorf("mkdir: %w",err)};dsn:=filepath.Join(dataDir,"tally.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);if err:=migrate(db);err!=nil{return nil,fmt.Errorf("migrate: %w",err)};return &DB{db},nil}
func migrate(db *sql.DB)error{_,err:=db.Exec(`CREATE TABLE IF NOT EXISTS forms(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT DEFAULT '',fields TEXT DEFAULT '[]',active INTEGER DEFAULT 1,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS responses(id INTEGER PRIMARY KEY AUTOINCREMENT,form_id INTEGER NOT NULL,data TEXT NOT NULL,ip TEXT DEFAULT '',created_at DATETIME DEFAULT CURRENT_TIMESTAMP);`);return err}
func(db *DB)ListForms()([]Form,error){rows,err:=db.Query(`SELECT f.id,f.name,f.description,f.fields,f.active,f.created_at,COUNT(r.id) FROM forms f LEFT JOIN responses r ON r.form_id=f.id GROUP BY f.id ORDER BY f.created_at DESC`);if err!=nil{return nil,err};defer rows.Close();var out[]Form;for rows.Next(){var f Form;rows.Scan(&f.ID,&f.Name,&f.Description,&f.Fields,&f.Active,&f.CreatedAt,&f.ResponseCount);out=append(out,f)};return out,nil}
func(db *DB)CreateForm(f *Form)error{if f.Fields==""{f.Fields="[]"};res,err:=db.Exec(`INSERT INTO forms(name,description,fields)VALUES(?,?,?)`,f.Name,f.Description,f.Fields);if err!=nil{return err};f.ID,_=res.LastInsertId();return nil}
func(db *DB)GetForm(id int64)(*Form,error){f:=&Form{};err:=db.QueryRow(`SELECT id,name,description,fields,active,created_at FROM forms WHERE id=?`,id).Scan(&f.ID,&f.Name,&f.Description,&f.Fields,&f.Active,&f.CreatedAt);if err==sql.ErrNoRows{return nil,nil};return f,err}
func(db *DB)UpdateFormFields(id int64,fields string)error{_,err:=db.Exec(`UPDATE forms SET fields=? WHERE id=?`,fields,id);return err}
func(db *DB)DeleteForm(id int64)error{_,err:=db.Exec(`DELETE FROM forms WHERE id=?`,id);return err}
func(db *DB)CreateResponse(r *Response)error{res,err:=db.Exec(`INSERT INTO responses(form_id,data,ip)VALUES(?,?,?)`,r.FormID,r.Data,r.IP);if err!=nil{return err};r.ID,_=res.LastInsertId();return nil}
func(db *DB)ListResponses(formID int64,limit int)([]Response,error){rows,err:=db.Query(`SELECT id,form_id,data,ip,created_at FROM responses WHERE form_id=? ORDER BY created_at DESC LIMIT ?`,formID,limit);if err!=nil{return nil,err};defer rows.Close();var out[]Response;for rows.Next(){var r Response;rows.Scan(&r.ID,&r.FormID,&r.Data,&r.IP,&r.CreatedAt);out=append(out,r)};return out,nil}
func(db *DB)CountForms()(int,error){var n int;db.QueryRow(`SELECT COUNT(*) FROM forms`).Scan(&n);return n,nil}
func(db *DB)CountResponses()(int,error){var n int;db.QueryRow(`SELECT COUNT(*) FROM responses`).Scan(&n);return n,nil}
type Field struct{Type string `json:"type"`;Label string `json:"label"`;Required bool `json:"required"`;Options[]string `json:"options,omitempty"`}
func ParseFields(s string)([]Field,error){var out[]Field;err:=json.Unmarshal([]byte(s),&out);return out,err}
